export const categoriesItemsStubs = [
  {
    category: 'Apple',
    sub_categories: [
      {
        title: 'iPhone',
        items: [
          'iPhone 13 2021',
          'iPhone 12 Series',
          'iPhone 11',
          'iPhone SE 2020',
          'iPhone XR',
        ],
      },
      {
        title: 'MacBook',
        items: ['MacBook Air 13 2020', 'MacBook Pro 13 2020'],
      },
      {
        title: 'iPad',
        items: [
          'iPad Pro 2021',
          'iPad 2021',
          'iPad Mini 2021',
          'iPad 2020',
          'iPad Air 2020',
        ],
      },
      { title: 'iMac', items: ['iMac 2021', 'iMac 2020'] },
      {
        title: 'Apple Watch',
        items: [
          'Watch Series 7',
          'Watch Series 6',
          'Watch Series 6 Nike',
          'Watch SE',
          'Watch Series 5',
          'Watch Series 4',
        ],
      },
      { title: 'AirPods', items: [] },
      {
        title: 'Accesorii Apple',
        items: [
          'Huse pentru telefon',
          'Huse pentru laptop',
          'Huse pentru tablete',
          'Mouse',
          'Tastaturi',
          'Adaptoare',
          'Încărcătoare',
          'Cabluri',
        ],
      },
      { title: 'Apple TV', items: [] },
    ],
  },
  {
    category: 'Telefoane',
    sub_categories: [
      {
        title: 'Smartphone-uri',
        items: [
          'Apple iPhone 13 2021',
          'Până la 5000 lei',
          'De la 5000 până la 10000 lei',
          'De la 10000 lei',
          'Cu baterie longevivă',
          'Noile Apple iPhone',
        ],
      },
      {
        title: 'Producători',
        items: [
          'Apple',
          'Samsung',
          'Xiaomi',
          'OnePlus',
          'Realme',
          'Oppo',
          'Huawei',
          'Poco',
        ],
      },
      {
        title: 'Accesorii pentru telefoane',
        items: [
          'Huse',
          'Folii protecție din sticlă',
          'PopSockets',
          'Selfie stick-uri',
          'Сăşti',
          'Carduri de memorie',
          'Acumulatoare externe',
          'Încărcătoare',
          'Adaptoare',
          'Cabluri GSM',
        ],
      },
      {
        title: 'Telefoane clasice',
        items: ['Dual SIM', 'Cu baterie longevivă'],
      },
      {
        title: 'Telefoane staționare',
        items: ['Telefoane DECT', 'Telefoane CORDER'],
      },
      { title: 'Certificat Cadou', items: ['500 lei', '1000 lei', '2000 lei'] },
    ],
  },
  {
    category: 'Laptopuri și Tablete',
    sub_categories: [
      {
        title: 'Laptopuri',
        items: [
          'MacBook',
          'Ultrabook-uri',
          'Laptopuri gaming',
          'Laptopuri business',
          'Laptopuri personale',
        ],
      },
      {
        title: 'Tablete',
        items: ['iPad', 'Tablete Android', 'eBook Readers', 'Tablete grafice'],
      },
      {
        title: 'Genți și rucsacuri',
        items: ['Genți pentru laptop', 'Rucsacuri'],
      },
      {
        title: 'Accesorii pentru laptop',
        items: [
          'HDD extern',
          'Memorii USB',
          'Încărcătoare',
          'Mouse-uri',
          'Huse',
          'Căști',
          'Suporturi de răcire (coolere)',
        ],
      },
      {
        title: 'Accesorii pentru tablete',
        items: [
          'Huse',
          'Сăști',
          'Cartele de memorie',
          'Baterii externe',
          'Stilusuri pentru tablete',
        ],
      },
      {
        title: 'Programe Soft',
        items: ['Sisteme de operare', 'Antivirus', 'Suite Office'],
      },
      { title: 'Certificat Cadou', items: ['500 lei', '1000 lei', '2000 lei'] },
    ],
  },
  {
    category: 'PC și periferice',
    sub_categories: [
      {
        title: 'Sisteme PC',
        items: ['Home and Office PC', 'Gaming PC', 'Mini PC', 'All-in-One PC'],
      },
      {
        title: 'Periferice',
        items: [
          'Monitoare',
          'Tastaturi',
          'Mouse-uri',
          'Mousepad',
          'Microfoane',
          'Camere web',
          'Memorii USB',
          'HDD extern',
          'UPS',
          'Carcase pentru unități de stocare',
        ],
      },
      {
        title: 'PC Components',
        items: [
          'Procesoare',
          'Plăci video',
          'Plăci de bază',
          'Memorie operativă',
          'Surse de alimentare',
          'Dispozitive de stocare',
          'Coolere',
          'Carcase',
          'Pastă termoconductoare',
        ],
      },
      {
        title: 'Echipamente de rețea',
        items: [
          'Switch',
          'Routere Wireless',
          'Wireless access point',
          'Adaptoare LAN',
          'NAS',
          'Extendere',
        ],
      },
      {
        title: 'Tehnică de birou',
        items: [
          'Ecrane de proiecție',
          'Fundaluri foto',
          'Imprimante',
          'Multifuncționale',
          'Proiectoare',
          'Imprimante 3D',
          'Accesorii pentru imprimare 3D',
          'Plottere',
        ],
      },
      {
        title: 'Programe Soft',
        items: [
          'Sisteme de operare',
          'Antivirus',
          'Suite Office',
          'Cinematograf online',
        ],
      },
    ],
  },
  {
    category: 'Televizoare',
    sub_categories: [
      {
        title: 'Televizoare',
        items: [
          'TV 8K',
          'TV 4K',
          'TV NanoCell',
          'TV QLED',
          'TV OLED',
          'Smart TV',
          'Android TV',
        ],
      },
      {
        title: 'Diagonale',
        items: [
          '24" - 32" (61 - 81 cm)',
          '40" - 49" (101 - 124 cm)',
          '50" - 58" (127 - 147 cm)',
          '65" - 75" (165 - 190 cm)',
          '82" - 86" (208 - 218 cm)',
        ],
      },
      {
        title: 'Producători',
        items: ['Samsung', 'Hisense', 'Sony', 'OZON', 'LG', 'TCL'],
      },
      {
        title: 'Sisteme audio',
        items: [
          'Soundbar',
          'Sisteme audio 2.0',
          'Sisteme audio 2.1',
          'Sisteme audio 3.1',
          'Sisteme audio 5.1',
        ],
      },
      {
        title: 'Accesorii TV',
        items: ['Media playere', 'Suporturi TV', 'Cinematograf online'],
      },
      { title: 'Certificat Cadou', items: ['500 lei', '1000 lei', '2000 lei'] },
    ],
  },
  {
    category: 'Tehnică de climatizare',
    sub_categories: [
      {
        title: 'Aparate de încălzire electrice',
        items: [
          'Încălzitoare cu ventilator',
          'Încălzitoare infraroșii',
          'Calorifere electrice cu ulei',
          'Convectoare',
          'Șeminee electrice',
        ],
      },
      {
        title: 'Ventilatoare',
        items: ['Ventilatoare de masă', 'Ventilatoare de podea'],
      },
      {
        title: 'Aparate de aer condiţionat',
        items: [
          'Aparate de aer conditionat mobile',
          'Capacitatea de răcire 7000 BTU',
          'Capacitatea de răcire 9000 BTU',
          'Capacitatea de răcire 12000 BTU',
          'Capacitatea de răcire 18000 BTU',
          'Capacitatea de răcire 24000 BTU',
          'Split-System',
        ],
      },
      {
        title: 'Încălzitoare de apă',
        items: ['Boilere cu acumulare', 'Încălzitoare de apă instant'],
      },
      {
        title: 'Aparate filtrare aer',
        items: [
          'Umidificatoare de aer',
          'Purificatoare de aer',
          'Dezumidificatoare',
        ],
      },
    ],
  },
  {
    category: 'Electrocasnice',
    sub_categories: [
      {
        title: 'Electrocasnice mari',
        items: [
          'Tehnică încorporabilă',
          'Mașini de spălat rufe',
          'Mașini de spălat rufe cu uscător',
          'Mașini de uscat rufe',
          'Frigidere',
          'Congelatoare',
          'Aragaze',
          'Mașini de spălat vase',
          'Hote',
          'Cuptoare cu microunde',
          'Cuptoare electrice',
          'Lăzi frigorifice',
          'Plite de masă',
        ],
      },
      {
        title: 'Electrocasnice mici pentru bucătărie',
        items: [
          'Feliatoare',
          'Cuptoare cu microunde',
          'Blendere',
          'Multicooker',
          'Râșnițe',
          'Ceainice electrice',
          'Aparatele de cafea',
          'Cafea',
          'Mixere de bucătărie',
          'Mașini de tocat carne',
          'Procesoare și roboți de bucătărie',
          'Grătare electrice',
          'Cântare de bucătărie',
          'Prăjitoare de pâine (toaster)',
          'Mașini de copt pâine',
          'ThermoPot',
          'Prăjitoare de sandwich-uri & waffe',
          'Storcătoare de fructe & legume',
          'Filtre de apă',
          'Aparate de preparat iaurt',
          'Veselă',
        ],
      },
      {
        title: 'Aparate de uz casnic',
        items: [
          'Aspiratoare cu sac',
          'Aspiratoare cu container',
          'Aspiratoare robot',
          'Aspiratoare verticale',
          'Accesorii pentru aspiratoare',
          'Fiare de călcat',
          'Stații de călcat',
          'Vaporizatoare',
          'Coșuri pentru rufe',
          'Uscătoare de rufe',
          'Mese de călcat',
          'Containere izotermice',
          'Genți frigorifice',
          'Genți termice',
          'Aparate de curățat scame',
          'Mașini de cusut',
          'Produse chimice de uz casnic',
        ],
      },
    ],
  },
  {
    category: 'Îngrijire personală și sănătate',
    sub_categories: [
      {
        title: 'Aparate de coafat',
        items: [
          'Uscătoare de păr',
          'Perii rotative',
          'Ondulatoare',
          'Plăci de îndreptat părul',
        ],
      },
      {
        title: 'Aparate de ras și tuns',
        items: [
          'Aparate de ras',
          'Trimmer facial',
          'Trimmere de nas şi urechi',
          'Aparate de tuns',
          'Epilatoare',
        ],
      },
      {
        title: 'Articole de sănătate',
        items: [
          'Periuțe de dinți electrice',
          'Cântare de podea',
          'Termometre',
          'Testere pentru apă',
          'Aparate de îngrijire facială',
          'Ingrijire corp',
          'Oglinzi',
          'Manichiură și pedichiură',
        ],
      },
      {
        title: 'Produse pentru adulți 18+',
        items: [
          'Vibratoare',
          'Vibrostimulatoare',
          'Jucării Anale',
          'Bile Vaginale',
          'Dildo-uri',
          'Seturi jucării pentru adulți',
          'Lubrifianți',
          'Masturbatoare',
          'Strapoane',
          'Lenjerie sexy',
          'Inele pentru penis',
          'Accesorii BDSM',
        ],
      },
      { title: 'Asigurare COVID-19', items: [] },
      { title: 'Certificat Cadou', items: ['500 lei', '1000 lei', '2000 lei'] },
    ],
  },
  {
    category: 'For Gamers',
    sub_categories: [
      {
        title: 'Sisteme Gaming',
        items: ['Laptopuri', 'Unitate PC', 'Monitoare'],
      },
      {
        title: 'Periferice gaming',
        items: [
          'Tastaturi',
          'Mouse-uri',
          'Mousepad-uri',
          'Căști',
          'Controller',
        ],
      },
      {
        title: 'Articole de gaming',
        items: ['Scaune', 'Haine', 'Articole fan'],
      },
      {
        title: 'Playstation',
        items: ['Sony PlayStation 5', 'Console', 'Accesorii', 'Jocuri'],
      },
      {
        title: 'XBOX',
        items: ['Xbox Series X și Series S', 'Console', 'Accesorii', 'Jocuri'],
      },
      { title: 'Nintendo', items: ['Console', 'Jocuri'] },
      { title: 'Certificat Cadou', items: ['500 lei', '1000 lei', '2000 lei'] },
    ],
  },
  {
    category: 'Instrumente electrice',
    sub_categories: [
      {
        title: 'Pentru casă',
        items: [
          'Aspiratoare industriale semiprofesionale',
          'Mașini de găurit și înșurubat',
          'Ciocane rotopercutoare și demolatoare',
          'Polizoare și foarfece',
          'Fierăstraie',
          'Freze',
          'Mașini de curățat cu presiune înaltă',
          'Șlefuitoare și rindele',
          'Suflante cu aer cald',
          'Compresoare',
          'Mașini de lustruit',
        ],
      },
      {
        title: 'Profesionale',
        items: [
          'Mașini de găurit și înșurubat',
          'Ciocane rotopercutoare și demolatoare',
          'Polizoare și foarfece',
          'Fierăstraie',
          'Agitatoare (mixere)',
          'Freze',
          'Aspiratoare industriale și sisteme de aspirare',
          'Rindele',
          'Suflante cu aer cald',
          'Mașini de curățat cu presiune',
          'Compresoare',
          'Fierăstraie pentru decupat',
        ],
      },
      {
        title: 'Pentru grădinărit',
        items: [
          'Mașini de tuns gard viu',
          'Mașini de tuns iarbă',
          'Tocătoare de grădină',
          'Fierăstraie cu lanț',
          'Suflante pentru frunze',
          'Pulverizatoare',
          'Motocultoare',
          'Motoburghie (foreze)',
          'Componente',
          'Trimmere de tuns iarba',
        ],
      },
    ],
  },
  {
    category: 'Produse Auto',
    sub_categories: [
      {
        title: 'Anvelope',
        items: [
          'Pentru autoturisme',
          'Pentru camionete',
          'Pentru SUV-uri (Off Road)',
          'De iarnă',
          'De vară',
          'All Season',
        ],
      },
      {
        title: 'Acumulatoare auto',
        items: ['Polaritatea inversă', 'Polaritatea directă'],
      },
      {
        title: 'Uleiuri de motor',
        items: ['Sintetice', 'Semisintetice', 'Minerale'],
      },
      {
        title: 'Auto Gadget-uri',
        items: [
          'Frigidere auto',
          'Camere Auto',
          'Căști Handsfree',
          'FM modulatoare',
          'Cabluri și adaptoare GSM',
          'Cartele de memorie',
          'Suporturi auto',
          'Playere auto',
        ],
      },
      {
        title: 'Aparate de spălat și aspiratoare',
        items: ['Mașini de spălat cu presiune'],
      },
      { title: 'Scaune auto pentru copii', items: [] },
      { title: 'Accesorii auto', items: ['Covorașe auto', 'Paravânturi auto'] },
    ],
  },
  {
    category: 'Gadgeturi, Foto și Turism',
    sub_categories: [
      {
        title: 'Ceasuri & Brățări smart',
        items: [
          'Xiaomi Mi Band 6',
          'Smartwatch-uri',
          'Brățări fitness',
          'Ceasuri smart pentru copii',
          'Accesorii',
          'Noile Apple Watch',
        ],
      },
      {
        title: 'Smart Home',
        items: [
          'Dispozitive de testare',
          'Huse pentru smart trackere',
          'Smart Trackers',
          'Light Control',
          'Media playere',
          'Senzori smart',
        ],
      },
      {
        title: 'Iluminare',
        items: [
          'Lămpi',
          'Benzi LED',
          'Lămpi circulare',
          'Becuri',
          'Lanterne',
          'Lămpi anti insecte',
        ],
      },
      {
        title: 'Foto-Video',
        items: [
          'Camere de supraveghere',
          'Camere foto',
          'Camere action',
          'Accesorii foto și video',
        ],
      },
      {
        title: 'Divertisment',
        items: ['Drone', 'Ochelari VR', 'Accesorii AR'],
      },
      {
        title: 'Optică și astronomie',
        items: ['Telescoape', 'Microscoape', 'Binocluri', 'Lunete'],
      },
      {
        title: 'IQOS',
        items: [
          'IQOS 3 DUO',
          'IQOS 3 MULTI',
          'IQOS 2.4 Plus',
          'Accesorii IQOS',
        ],
      },
      { title: 'Narghilele electronice', items: ['Narghilele electronice'] },
      {
        title: 'Genți și Rucsacuri',
        items: ['Genți pentru călătorii', 'Rucsacuri'],
      },
      { title: 'Lil', items: [] },
      { title: 'Stații Radio', items: [] },
      { title: 'Acumulatoare', items: [] },
      { title: 'Baterii', items: [] },
    ],
  },
  {
    category: 'Audio',
    sub_categories: [
      {
        title: 'Căști',
        items: ['Wireless', 'Cu fir', 'Sport', 'Gaming', 'Cu microfon'],
      },
      {
        title: 'Boxe',
        items: ['Boxe portabile', 'Boxe smart', 'Boxe pentru Party'],
      },
      {
        title: 'Producători',
        items: ['Harman Kardon', 'House of Marley', 'JBL', 'SkullCandy', 'JAM'],
      },
      {
        title: 'Sisteme audio',
        items: [
          'Soundbar',
          'Sisteme audio 2.0',
          'Sisteme audio 2.1',
          'Sisteme audio 5.1',
        ],
      },
      { title: 'Audio HI-FI', items: ['Discuri vinil'] },
      { title: 'Certificat Cadou', items: ['500 lei', '1000 lei', '2000 lei'] },
      { title: 'Huse pentru căști', items: [] },
    ],
  },
  {
    category: 'Decorațiuni și Accesorii',
    sub_categories: [
      {
        title: 'Brazi de crăciun',
        items: [
          'Verzi',
          'Albi',
          'Albaștri',
          'de la 60 cm până la 180 cm',
          'de la 210 cm până la 280 cm',
          'de la 300 cm și mai mari',
        ],
      },
      {
        title: 'Jucarii de brad',
        items: ['Set globuri', 'Set decorațiuni', 'Vârfuri'],
      },
      {
        title: 'Focuri de artificii',
        items: [
          'de la 12 la 30 focuri',
          'de la 36 la 66 focuri',
          'de la 72 la 147 focuri',
          'de la 150 la 300 focuri',
        ],
      },
      { title: 'Ghirlande LED', items: ['Plasă', 'String-Light'] },
    ],
  },
  {
    category: 'Mobilă',
    sub_categories: [
      {
        title: 'Mobilier de birou',
        items: ['Fotolii de birou', 'Mese de birou'],
      },
      {
        title: 'Mobilă de bucătărie',
        items: ['Mese de bucătărie', 'Scaune de bucătărie', 'Taburete'],
      },
    ],
  },
  {
    category: 'Produse pentru copii',
    sub_categories: [
      {
        title: 'Jucării',
        items: [
          'Mașinuțe',
          'Figurine',
          'Jucării antistres',
          'Constructori',
          'Jucării interactive',
          'Jucării electrice',
          'Elicoptere şi Avioane',
          'Puzzle',
          'Roboți',
        ],
      },
      {
        title: 'Jucării de exterior',
        items: ['Tobogane', 'Trambuline', 'Căsuțe pentru copii', 'Balansoare'],
      },
      {
        title: 'Transport pentru copii',
        items: [
          'Biciclete',
          'Biciclete fără pedale',
          'Trotinete pentru copii',
          'Mașini electrice pentru copii',
          'Motociclete pentru copii',
          'Tolocare',
        ],
      },
      {
        title: 'Pătuțuri pentru copii',
        items: [
          'Saltele pentru copii',
          'Perne pentru bebeluși',
          'Lenjerie de pat pentru copii',
          'Babynest',
        ],
      },
      { title: 'Cărucioare pentru copii', items: ['Genți pentru mămici'] },
      { title: 'Scaune de masă', items: [] },
      { title: 'Țarcuri pentru copii', items: [] },
      { title: 'Scaune auto pentru copii', items: [] },
      { title: 'Leagăne pentru bebeluși', items: [] },
      { title: 'Covoraşe pentru joc', items: [] },
      { title: 'Slingi și Ergo pentru bebeluși', items: [] },
      { title: 'Premergătoare și Jumpere', items: [] },
    ],
  },
  {
    category: 'Transport',
    sub_categories: [
      {
        title: 'Transport electric',
        items: [
          'Trotinete',
          'Hoverboard-uri',
          'Scutere',
          'Biciclete',
          'Mașini electrice pentru copii',
          'Motociclete pentru copii',
        ],
      },
      {
        title: 'Transport clasic',
        items: [
          'Biciclete',
          'Biciclete pentru copii',
          'Trotinete pentru copii',
        ],
      },
      {
        title: 'Accesorii',
        items: [
          'Huse hoverboard',
          'Echipamente de protecție',
          'Accesorii pentru bicicletă',
        ],
      },
    ],
  },
];
