describe('filter menu', () => {
    beforeEach(() => {
        cy.visit('http://localhost:8080/')
        cy.get('#input-23')
            .type('test{enter}')
    })

    context('default set values of sorting', () => {
        it('sort by field default Price', () => {
            cy.get('.v-select__selection')
                .should('have.text', 'Price')
        })

        it('sort order default ASC', () => {
            cy.get('#sortOrder > .v-btn__content')
                .should('include.text', 'Asc')
        })
    })

    context('default set values of filter', () => {
        it('min price === 23', () => {
            cy.get('#input-61')
                .should('have.value', 23)
        })

        it('max price === 43846', () => {
            cy.get('#input-62')
                .should('have.value', 43846)
        })

        it('default currency === L', () => {
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(1)')
                .should('have.text', 'L')
        })

        it('button of default currency disabled', () => {
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(1)')
                .should('have.attr', 'disabled', 'disabled')
        })
    })

    it('default (asc) list', () => {
        cy.get('#numberOfItems')
            .should('include.text', '610')
        cy.get(':nth-child(1) > .mx-auto > :nth-child(3)')
            .should('include.text', '23.00 L')
        cy.get(':nth-child(3) > .mx-auto > :nth-child(3)')
            .should('include.text', '24.00 L')
        cy.get(':nth-child(6) > .mx-auto > :nth-child(3)')
            .should('include.text', '30.00 L')
        cy.get(':nth-child(35) > .mx-auto > :nth-child(3)')
            .should('include.text', '59.00 L')
        cy.get(':nth-child(609) > .mx-auto > :nth-child(3)')
            .should('include.text', '41,431.00 L')
        cy.get(':nth-child(610) > .mx-auto > :nth-child(3)')
            .should('include.text', '43,846.00 L')
    })

    it('changes order to desc', () => {
        cy.get('#sortOrder').click()
        cy.get('#numberOfItems')
            .should('include.text', '610')
        cy.get(':nth-child(1) > .mx-auto > :nth-child(3)')
            .should('include.text', '43,846.00 L')
        cy.get(':nth-child(2) > .mx-auto > :nth-child(3)')
            .should('include.text', '41,431.00 L')
        cy.get(':nth-child(6) > .mx-auto > :nth-child(3)')
            .should('include.text', '32,258.00 L')
        cy.get(':nth-child(35) > .mx-auto > :nth-child(3)')
            .should('include.text', '21,736.00 L')
        cy.get(':nth-child(608) > .mx-auto > :nth-child(3)')
            .should('include.text', '24.00 L')
        cy.get(':nth-child(610) > .mx-auto > :nth-child(3)')
            .should('include.text', '23.00 L')
    })

    it('changes sortBy to name', () => {
        cy.get(':nth-child(1) > .mx-auto > a > .v-card__title')
            .should('include.text', 'Xcover husa p/u iPhone XS Max, TPU ultra-thin K Gray')
        cy.get(':nth-child(3) > .v-input > .v-input__control > .v-input__slot > .v-select__slot > .v-input__append-inner > .v-input__icon > .v-icon')
            .click()
        cy.contains('Name')
            .click()
        cy.get(':nth-child(1) > .mx-auto > a > .v-card__title')
            .should('include.text', '"Easy" Car Charger for Apple iPhone/iPod with Lightning Connector, black Hama')
        cy.get(':nth-child(610) > .mx-auto > a > .v-card__title')
            .should('include.text', 'Умные часы Apple Watch Series 51.78"/ MWVE2/ Sport Band Золотой')
    })

    it('unchecking + checking shops checkboxes', () => {
        cy.get('.mx-3 > .v-input__control > .v-input__slot')
            .click()
        // unchecking enter
        cy.get('#list-item-2514-0')
            .click()
        cy.get('#numberOfItems')
            .should('include.text', '590')
        cy.get('.pt-6')
            .should('not.include.text', 'enter')
        // unchecking darwin
        cy.get('#list-item-2514-1')
            .click()
        cy.get('#numberOfItems')
            .should('include.text', '570')
        cy.get('.pt-6')
            .should('not.include.text', 'darwin')
            .should('not.include.text', 'enter')
        // unchecking shopit
        cy.get('#list-item-2514-2')
            .click()
        cy.get('#numberOfItems')
            .should('include.text', '0')
        cy.get('.pt-6')
            .should('not.include.text', 'darwin')
            .should('not.include.text', 'enter')
            .should('not.include.text', 'shopit')
        // checking enter
        cy.get('#list-item-2514-0')
            .click()
        cy.get('#numberOfItems')
            .should('include.text', '20')
        cy.get('.pt-6')
            .should('include.text', 'enter')
        // checking shopit
        cy.get('#list-item-2514-2')
            .click()
        cy.get('#numberOfItems')
            .should('include.text', '590')
        cy.get('.pt-6')
            .should('include.text', 'enter')
            .should('include.text', 'shopit')
        // checking darwin
        cy.get('#list-item-2514-1')
            .click()
        cy.get('#numberOfItems')
            .should('include.text', '610')
        cy.get('.pt-6')
            .should('include.text', 'enter')
            .should('include.text', 'shopit')
            .should('include.text', 'darwin')
    })

    context('changing price limits', () => {
        it('changes minimal price', () => {
            cy.get('#input-61')
                .clear()
                .type('500{enter}')
            cy.get('#numberOfItems')
                .should('include.text', '127')
            cy.get(':nth-child(1) > .mx-auto > :nth-child(3)')
                .should('include.text', '588.00 L')
            cy.get(':nth-child(127) > .mx-auto > :nth-child(3)')
                .should('include.text', '43,846.00 L')
        })
        it('changes maximal price', () => {
            cy.get('#input-62')
                .clear()
                .type('1000{enter}')
            cy.get('#numberOfItems')
                .should('include.text', '491')
            cy.get(':nth-child(1) > .mx-auto > :nth-child(3)')
                .should('include.text', '23.00 L')
            cy.get(':nth-child(491) > .mx-auto > :nth-child(3)')
                .should('include.text', '997.00 L')
        })
        it('changes minimal and maximal price', () => {
            cy.get('#input-61')
                .clear()
                .type('500{enter}')
            cy.get('#input-62')
                .clear()
                .type('1000{enter}')
            cy.get('#numberOfItems')
                .should('include.text', '8')
            cy.get(':nth-child(1) > .mx-auto > :nth-child(3)')
                .should('include.text', '588.00 L')
            cy.get(':nth-child(8) > .mx-auto > :nth-child(3)')
                .should('include.text', '997.00 L')
        })
    })

    context('changes currencies', () => {
        it('current currency is L and the [L] button is disabled', () => {
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(1)')
                .should('have.attr', 'disabled', 'disabled')
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(2)')
                .should('not.have.attr', 'disabled', 'disabled')
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(3)')
                .should('not.have.attr', 'disabled', 'disabled')
            cy.get(':nth-child(521) > .mx-auto > :nth-child(3)')
                .should('include.text', '8,499.00 L')
        })
        it('changing currency to €', () => {
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(2)')
                .click()
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(1)')
                .should('not.have.attr', 'disabled', 'disabled')
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(2)')
                .should('have.attr', 'disabled', 'disabled')
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(3)')
                .should('not.have.attr', 'disabled', 'disabled')
            cy.get(':nth-child(521) > .mx-auto > :nth-child(3)')
                .should('include.text', '422.50 €')
            cy.get('.pt-6')
                .should('not.include.text', '.00 L')
                .should('not.include.text', '$')
        })
        it('changing currency to $', () => {
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(3)')
                .click()
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(1)')
                .should('not.have.attr', 'disabled', 'disabled')
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(2)')
                .should('not.have.attr', 'disabled', 'disabled')
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(3)')
                .should('have.attr', 'disabled', 'disabled')
            cy.get(':nth-child(521) > .mx-auto > :nth-child(3)')
                .should('include.text', '479.39 $')
            cy.get('.pt-6')
                .should('not.include.text', '.00 L')
                .should('not.include.text', '€')
        })
        it('changing currency from € to $ to L', () => {
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(2)')
                .click()
            cy.get(':nth-child(521) > .mx-auto > :nth-child(3)')
                .should('include.text', '422.50 €')

            cy.get('.pt-3 > .d-flex.v-card > :nth-child(3)')
                .click()
            cy.get(':nth-child(521) > .mx-auto > :nth-child(3)')
                .should('include.text', '479.39 $')

            cy.get('.pt-3 > .d-flex.v-card > :nth-child(1)')
                .click()
            cy.get(':nth-child(521) > .mx-auto > :nth-child(3)')
                .should('include.text', '8,499.00 L')
        })
    })
})