describe('filter menu', () => {
    beforeEach(() => {
        cy.visit('http://localhost:8080/')
        cy.get('#input-24')
            .type('test{enter}')
    })

    context('default set values of sorting', () => {
        it('sort by field default Price', () => {
            cy.get('.v-select__selection')
                .should('have.text', 'Preț')
        })

        it('sort order default ASC', () => {
            cy.get('#sortOrder > .v-btn__content')
                .should('include.text', 'ASC')
        })
    })

    context('default set values of filter', () => {
        it('min price === 89', () => {
            cy.get('#input-66')
                .should('have.value', 89)
        })

        it('max price === 46999', () => {
            cy.get('#input-67')
                .should('have.value', 46999)
        })

        it('default currency === L', () => {
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(1)')
                .should('have.text', 'L')
        })

        it('button of default currency disabled', () => {
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(1)')
                .should('have.attr', 'disabled', 'disabled')
        })
    })

    it('default (asc) list', () => {
        cy.get('#numberOfItems')
            .should('include.text', '82')
        cy.get(':nth-child(1) > .mx-auto > :nth-child(3)')
            .should('include.text', '89.00 L')
        cy.get(':nth-child(3) > .mx-auto > :nth-child(3)')
            .should('include.text', '99.00 L')
        cy.get(':nth-child(6) > .mx-auto > :nth-child(3)')
            .should('include.text', '112.00 L')
        cy.get(':nth-child(35) > .mx-auto > :nth-child(3)')
            .should('include.text', '577.00 L')
        cy.get(':nth-child(81) > .mx-auto > :nth-child(3)')
            .should('include.text', '45,999.00 L')
        cy.get(':nth-child(82) > .mx-auto > :nth-child(3)')
            .should('include.text', '46,999.00 L')
    })

    it('changes order to desc', () => {
        cy.get('#sortOrder').click()
        cy.get('#numberOfItems')
            .should('include.text', '82')
        cy.get(':nth-child(1) > .mx-auto > :nth-child(3)')
            .should('include.text', '46,999.00 L')
        cy.get(':nth-child(2) > .mx-auto > :nth-child(3)')
            .should('include.text', '45,999.00 L')
        cy.get(':nth-child(6) > .mx-auto > :nth-child(3)')
            .should('include.text', '39,999.00 L')
        cy.get(':nth-child(35) > .mx-auto > :nth-child(3)')
            .should('include.text', '4,199.00 L')
        cy.get(':nth-child(81) > .mx-auto > :nth-child(3)')
            .should('include.text', '99.00 L')
        cy.get(':nth-child(82) > .mx-auto > :nth-child(3)')
            .should('include.text', '89.00 L')
    })

    it('changes sortBy to name', () => {
        cy.get(':nth-child(1) > .mx-auto > a > .v-card__title')
            .should('include.text', 'Casti Hoco de la 89 lei. Наушники Hoco от 89 лей. Отличное качество!')
        cy.get(':nth-child(3) > .v-input > .v-input__control > .v-input__slot > .v-select__slot > .v-input__append-inner > .v-input__icon > .v-icon')
            .click()
        cy.contains('Denumire')
            .click()
        cy.get(':nth-child(1) > .mx-auto > a > .v-card__title')
            .should('include.text', 'Apple încărcător bloc+ usb Original !')
        cy.get(':nth-child(82) > .mx-auto > a > .v-card__title')
            .should('include.text', 'Чехол на iPhone 11 , iPhone 12 , iPhone 13 , pro max , pro')
    })

    it('unchecking + checking shops checkboxes', () => {
        cy.get('.mx-3 > .v-input__control > .v-input__slot')
            .click()
        // unchecking enter
        cy.get('#list-item-104-0')
            .click()
        cy.get('#numberOfItems')
            .should('include.text', '62')
        cy.get('.pt-6')
            .should('not.include.text', 'enter')
        // unchecking darwin
        cy.get('#list-item-104-1')
            .click()
        cy.get('#numberOfItems')
            .should('include.text', '42')
        cy.get('.pt-6')
            .should('not.include.text', 'darwin')
            .should('not.include.text', 'enter')
        // unchecking shopit
        cy.get('#list-item-104-2')
            .click()
        cy.get('#numberOfItems')
            .should('include.text', '22')
        cy.get('.pt-6')
            .should('not.include.text', 'darwin')
            .should('not.include.text', 'enter')
            .should('not.include.text', 'shopit')
        // checking enter
        cy.get('#list-item-104-0')
            .click()
        cy.get('#numberOfItems')
            .should('include.text', '42')
        cy.get('.pt-6')
            .should('include.text', 'enter')
        // checking shopit
        cy.get('#list-item-104-2')
            .click()
        cy.get('#numberOfItems')
            .should('include.text', '62')
        cy.get('.pt-6')
            .should('include.text', 'enter')
            .should('include.text', 'shopit')
        // checking darwin
        cy.get('#list-item-104-1')
            .click()
        cy.get('#numberOfItems')
            .should('include.text', '82')
        cy.get('.pt-6')
            .should('include.text', 'enter')
            .should('include.text', 'shopit')
            .should('include.text', 'darwin')
    })

    context('changing price limits', () => {
        it('changes minimal price', () => {
            cy.get('#input-66', {timeout: 5000})
                .should('have.value', 89)
                .clear()
                .type('500{enter}')
            cy.get('#numberOfItems')
                .should('include.text', '48')
            cy.get(':nth-child(1) > .mx-auto > :nth-child(3)')
                .should('include.text', '577.00 L')
            cy.get(':nth-child(25) > .mx-auto > :nth-child(3)')
                .should('include.text', '24,999.00 L')
        })
        it('changes maximal price', () => {
            cy.get('#input-67', {timeout: 5000})
                .should('have.value', 46999)
                .clear()
                .type('1000{enter}')
            cy.get('#numberOfItems')
                .should('include.text', '39')
            cy.get(':nth-child(1) > .mx-auto > :nth-child(3)')
                .should('include.text', '89.00 L')
            cy.get(':nth-child(39) > .mx-auto > :nth-child(3)')
                .should('include.text', '949.00 L')
        })
        it('changes minimal and maximal price', () => {
            cy.get('#input-66', {timeout: 5000})
                .should('have.value', 89)
                .clear()
                .type('500{enter}')
            cy.get('#input-67', {timeout: 5000})
                .should('have.value', 46999)
                .clear()
                .type('1000{enter}')
            cy.get('#numberOfItems')
                .should('include.text', '5')
            cy.get(':nth-child(1) > .mx-auto > :nth-child(3)')
                .should('include.text', '577.00 L')
            cy.get(':nth-child(5) > .mx-auto > :nth-child(3)')
                .should('include.text', '949.00 L')
        })
    })

    context('changes currencies', () => {
        it('current currency is L and the [L] button is disabled', () => {
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(1)')
                .should('have.attr', 'disabled', 'disabled')
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(2)')
                .should('not.have.attr', 'disabled', 'disabled')
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(3)')
                .should('not.have.attr', 'disabled', 'disabled')
            cy.get(':nth-child(65) > .mx-auto > :nth-child(3)')
                .should('include.text', '29,999.00 L')
        })
        it('changing currency to €', () => {
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(2)')
                .click()
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(1)')
                .should('not.have.attr', 'disabled', 'disabled')
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(2)')
                .should('have.attr', 'disabled', 'disabled')
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(3)')
                .should('not.have.attr', 'disabled', 'disabled')
            cy.get(':nth-child(65) > .mx-auto > :nth-child(3)')
                .should('include.text', '1,491.30 €')
            cy.get('.pt-6')
                .should('not.include.text', '.00 L')
                .should('not.include.text', '$')
        })
        it('changing currency to $', () => {
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(3)')
                .click()
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(1)')
                .should('not.have.attr', 'disabled', 'disabled')
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(2)')
                .should('not.have.attr', 'disabled', 'disabled')
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(3)')
                .should('have.attr', 'disabled', 'disabled')
            cy.get(':nth-child(65) > .mx-auto > :nth-child(3)')
                .should('include.text', '1,692.11 $')
            cy.get('.pt-6')
                .should('not.include.text', '.00 L')
                .should('not.include.text', '€')
        })
        it('changing currency from € to $ to L', () => {
            cy.get('.pt-3 > .d-flex.v-card > :nth-child(2)')
                .click()
            cy.get(':nth-child(65) > .mx-auto > :nth-child(3)')
                .should('include.text', '1,491.30 €')

            cy.get('.pt-3 > .d-flex.v-card > :nth-child(3)')
                .click()
            cy.get(':nth-child(65) > .mx-auto > :nth-child(3)')
                .should('include.text', '1,692.11 $')

            cy.get('.pt-3 > .d-flex.v-card > :nth-child(1)')
                .click()
            cy.get(':nth-child(65) > .mx-auto > :nth-child(3)')
                .should('include.text', '29,999.00 L')
        })
    })
})